In [27]:
import pandas as pd 
import numpy as np 
import random 
import os 
import json 
import matplotlib.pyplot as plt 
import seaborn as sns 
from datetime import datetime, timedelta 
import funcoes

In [28]:
caminho_do_arquivo = '../dados/raw/vendas.csv'
df = pd.read_csv(caminho_do_arquivo)
df_original = df.copy()

In [29]:
# Visão geral do df
df_original

,id_venda,data_venda,cliente,produto,categoria,regiao,quantidade,preco_unitario
0,1,2024-01-13,Cliente_024,Mouse,Periféricos,Norte,2.0,120.0
1,2,2024-08-04,Cliente_018,Notebook,Computadores,Sul,NaN,3500.0
2,3,DATA INVALIDA,Cliente_026,Mouse,Periféricos,Sul,9.0,120.0
3,4,2024-06-23,Cliente_013,Mouse,Periféricos,Sudeste,7.0,120.0
4,5,2024-11-05,Cliente_030,Tablet,Celulares,Centro-Oeste,6.0,1800.0
...,...,...,...,...,...,...,...,...
145,146,2024-08-09,Cliente_019,Notebook,Computadores,Norte,2.0,3500.0
146,147,2024-12-09,Cliente_028,Teclado,Periféricos,Sudeste,6.0,250.0
147,148,2024-06-08,Cliente_008,Tablet,Celulares,Sudeste,10.0,1800.0
148,149,2024-07-07,Cliente_018,Tablet,Celulares,Norte,9.0,1800.0
149,150,2024-01-14,Cliente_009,Teclado,Periféricos,Nordeste,9.0,250.0

In [30]:
# Informações relevantes para investigar os dados
funcoes.analise_dados(df_original)

,Tipos de Dados,Qtd_Não_Nulos,Valores Únicos,Qtd_Nulos,% Nulos,Duplicados
id_venda,int64,150,150,0,0.0%,0
data_venda,object,150,113,0,0.0%,0
cliente,object,150,30,0,0.0%,0
produto,object,150,9,0,0.0%,0
categoria,object,150,3,0,0.0%,0
regiao,object,150,5,0,0.0%,0
quantidade,float64,144,10,6,4.0%,0
preco_unitario,float64,147,6,3,2.0%,0

In [32]:
# Verificando nulos e duplos
todas_linhas_com_nulo = df_original[df_original.isna().any(axis=1)]
display(todas_linhas_com_nulo)

#linhas_duplicadas = df_original[df_original.duplicated(keep=False)]
#display(linhas_duplicadas)

,id_venda,data_venda,cliente,produto,categoria,regiao,quantidade,preco_unitario
1,2,2024-08-04,Cliente_018,Notebook,Computadores,Sul,NaN,3500.0
21,22,DATA INVALIDA,Cliente_023,Smartphone,Celulares,Sudeste,NaN,2200.0
48,49,2024-05-15,Cliente_014,Smartphone,Celulares,Norte,NaN,2200.0
63,64,2024-10-26,Cliente_016,Monitor,Computadores,Sudeste,7.0,NaN
78,79,2024-06-21,Cliente_026,Teclado,Periféricos,Nordeste,NaN,250.0
84,85,2024-07-03,Cliente_002,Tablet,Celulares,Norte,4.0,NaN
95,96,2024-08-12,Cliente_009,Teclado,Periféricos,Sudeste,8.0,NaN
113,114,2024-10-04,Cliente_008,Tablet,Celulares,Sudeste,NaN,1800.0
126,127,2024-07-21,Cliente_022,Tablet,Celulares,Nordeste,NaN,1800.0

In [33]:
# Inspecionando elementos e checagem geral
funcoes.contagem_valores(df_original)

--- RELATÓRIO DE VALORES ÚNICOS E CONTAGENS ---

[ ID_VENDA ] -> 150 valores. (Omitido)

[ DATA_VENDA ]
'2024-05-15' (10 letras): 5  |  'DATA INVALIDA' (13 letras): 4  |  '2024-11-22' (10 letras): 4
'2024-02-08' (10 letras): 3  |  '2024-10-26' (10 letras): 3  |  '2024-11-01' (10 letras): 2
'2024-07-21' (10 letras): 2  |  '2024-05-30' (10 letras): 2  |  '2024-09-16' (10 letras): 2
'2024-07-29' (10 letras): 2  |  '2024-05-05' (10 letras): 2  |  '2024-05-08' (10 letras): 2
'2024-02-25' (10 letras): 2  |  '2024-07-23' (10 letras): 2  |  '2024-10-22' (10 letras): 2
'2024-01-17' (10 letras): 2  |  '2024-11-05' (10 letras): 2  |  '2024-08-28' (10 letras): 2
'2024-08-08' (10 letras): 2  |  '2024-04-22' (10 letras): 2  |  '2024-12-03' (10 letras): 2
'2024-03-07' (10 letras): 2  |  '2024-03-20' (10 letras): 2  |  '2024-06-16' (10 letras): 2
'2024-07-04' (10 letras): 2  |  '2024-11-27' (10 letras): 2  |  '2024-05-27' (10 letras): 2
'2024-06-08' (10 letras): 2  |  '2024-06-30' (10 letras): 1  |  '2024-05-16' (10 letras): 1
'2024-01-25' (10 letras): 1  |  '2024-03-24' (10 letras): 1  |  '2024-01-13' (10 letras): 1
'2024-06-02' (10 letras): 1  |  '2024-11-14' (10 letras): 1  |  '2024-01-21' (10 letras): 1
'2024-05-02' (10 letras): 1  |  '2024-10-31' (10 letras): 1  |  '2024-09-05' (10 letras): 1
'2024-05-01' (10 letras): 1  |  '2024-12-15' (10 letras): 1  |  '2024-07-16' (10 letras): 1
'2024-07-05' (10 letras): 1  |  '2024-04-17' (10 letras): 1  |  '2024-08-04' (10 letras): 1
'2024-06-23' (10 letras): 1  |  '2024-05-28' (10 letras): 1  |  '2024-03-26' (10 letras): 1
'2024-08-14' (10 letras): 1  |  '2024-08-25' (10 letras): 1  |  '2024-11-18' (10 letras): 1
'2024-04-25' (10 letras): 1  |  '2024-03-27' (10 letras): 1  |  '2024-12-12' (10 letras): 1
'2024-12-27' (10 letras): 1  |  '2024-04-30' (10 letras): 1  |  '2024-08-06' (10 letras): 1
'2024-01-10' (10 letras): 1  |  '2024-04-12' (10 letras): 1  |  '2024-12-24' (10 letras): 1
'2024-01-22' (10 letras): 1  |  '2024-02-24' (10 letras): 1  |  '2024-07-18' (10 letras): 1
'2024-08-27' (10 letras): 1  |  '2024-02-12' (10 letras): 1  |  '2024-11-26' (10 letras): 1
'2024-06-21' (10 letras): 1  |  '2024-11-29' (10 letras): 1  |  '2024-10-10' (10 letras): 1
'2024-04-04' (10 letras): 1  |  '2024-07-03' (10 letras): 1  |  '2024-06-01' (10 letras): 1
'2024-09-04' (10 letras): 1  |  '2024-10-12' (10 letras): 1  |  '2024-08-12' (10 letras): 1
'2024-03-30' (10 letras): 1  |  '2024-12-11' (10 letras): 1  |  '2024-02-16' (10 letras): 1
'2024-02-29' (10 letras): 1  |  '2024-01-28' (10 letras): 1  |  '2024-10-08' (10 letras): 1
'2024-05-04' (10 letras): 1  |  '2024-06-13' (10 letras): 1  |  '2024-08-30' (10 letras): 1
'2024-03-05' (10 letras): 1  |  '2024-01-08' (10 letras): 1  |  '2024-12-20' (10 letras): 1
'2024-10-04' (10 letras): 1  |  '2024-11-20' (10 letras): 1  |  '2024-02-10' (10 letras): 1
'2024-11-23' (10 letras): 1  |  '2024-07-14' (10 letras): 1  |  '2024-10-16' (10 letras): 1
'2024-11-06' (10 letras): 1  |  '2024-11-17' (10 letras): 1  |  '2024-03-25' (10 letras): 1
'2024-04-23' (10 letras): 1  |  '2024-01-24' (10 letras): 1  |  '2024-08-20' (10 letras): 1
'2024-09-07' (10 letras): 1  |  '2024-04-07' (10 letras): 1  |  '2024-06-19' (10 letras): 1
'2024-04-20' (10 letras): 1  |  '2024-10-28' (10 letras): 1  |  '2024-08-31' (10 letras): 1
'2024-06-03' (10 letras): 1  |  '2024-09-08' (10 letras): 1  |  '2024-11-15' (10 letras): 1
'2024-06-09' (10 letras): 1  |  '2024-08-09' (10 letras): 1  |  '2024-12-09' (10 letras): 1
'2024-07-07' (10 letras): 1  |  '2024-01-14' (10 letras): 1

[ CLIENTE ]
'Cliente_024' (11 letras): 8  |  'Cliente_009' (11 letras): 8  |  'Cliente_029' (11 letras): 7
'Cliente_019' (11 letras): 7  |  'Cliente_020' (11 letras): 7  |  'Cliente_015' (11 letras): 7
'Cliente_022' (11 letras): 7  |  'Cliente_014' (11 letras): 7  |  'Cliente_008' (11 letras): 6
'Cliente_026' (11 letras): 6  |  'Cliente_001' (11 letras): 6  |  'Cliente_005' (11 letras): 6
'Cliente_013' (11 letras): 6  |  'Cliente_018' (11 letras): 6  |  'Cliente_017' (11 letras): 5
'Cliente_016' (11 letras): 5  |  'Cliente_003' (11 letras): 5  |  'Cliente_004' (11 letras): 5
'Cliente_025' (11 letras): 5  |  'Cliente_030' (11 letras): 4  |  'Cliente_023' (11 letras): 4
'Cliente_027' (11 letras): 3  |  'Cliente_028' (11 letras): 3  |  'Cliente_002' (11 letras): 3
'Cliente_007' (11 letras): 3  |  'Cliente_012' (11 letras): 3  |  'Cliente_011' (11 letras): 2
'Cliente_006' (11 letras): 2  |  'Cliente_021' (11 letras): 2  |  'Cliente_010' (11 letras): 2

[ PRODUTO ]
'Notebook' (8 letras): 27  |  'Smartphone' (10 letras): 25  |  'Tablet' (6 letras): 25
'Mouse' (5 letras): 24  |  'Monitor' (7 letras): 24  |  'Teclado' (7 letras): 22
'Tablet ' (7 letras): 1  |  'Smartphone ' (11 letras): 1  |  ' Smartphone ' (12 letras): 1

[ CATEGORIA ]
'Celulares' (9 letras): 53  |  'Computadores' (12 letras): 51  |  'Periféricos' (11 letras): 46

[ REGIAO ]
'Sudeste' (7 letras): 42  |  'Norte' (5 letras): 35  |  'Centro-Oeste' (12 letras): 27
'Sul' (3 letras): 23  |  'Nordeste' (8 letras): 23

[ QUANTIDADE ]
'8.0' (3 letras): 21  |  '4.0' (3 letras): 20  |  '2.0' (3 letras): 19
'5.0' (3 letras): 17  |  '9.0' (3 letras): 12  |  '6.0' (3 letras): 12
'7.0' (3 letras): 12  |  '3.0' (3 letras): 12  |  '10.0' (4 letras): 10
'1.0' (3 letras): 9

[ PRECO_UNITARIO ]
'3500.0' (6 letras): 27  |  '2200.0' (6 letras): 27  |  '1800.0' (6 letras): 25
'120.0' (5 letras): 24  |  '1200.0' (6 letras): 23  |  '250.0' (5 letras): 21

In [34]:
# Convertendo o para data (NaT)
df_original['data_venda'] = pd.to_datetime(df_original['data_venda'], errors='coerce')
print(df_original['data_venda'].dtype)

datetime64[ns]

In [35]:
# Retirando espaço vazio
df_original['produto'] = df_original['produto'].str.strip()

In [ ]:
# Valores presentes naquele elemento
df_limpo = df_original.drop(columns=['id_venda'])

df_agrupado = df_limpo.groupby('produto').agg(lambda x: list(x.unique()))

display(df_agrupado)

,data_venda,cliente,categoria,regiao,quantidade,preco_unitario
produto,,,,,,
Monitor,"[2024-01-25 00:00:00, 2024-11-01 00:00:00, 202...","[Cliente_020, Cliente_001, Cliente_009, Client...",[Computadores],"[Sudeste, Centro-Oeste, Sul, Nordeste, Norte]","[2.0, 7.0, 6.0, 1.0, 3.0, 8.0, 10.0, 4.0, 5.0,...","[1200.0, nan]"
Mouse,"[2024-01-13 00:00:00, NaT, 2024-06-23 00:00:00...","[Cliente_024, Cliente_026, Cliente_013, Client...",[Periféricos],"[Norte, Sul, Sudeste, Nordeste, Centro-Oeste]","[2.0, 9.0, 7.0, 5.0, 8.0, 3.0, 6.0, 4.0, 1.0]",[120.0]
Notebook,"[2024-08-04 00:00:00, 2024-05-30 00:00:00, 202...","[Cliente_018, Cliente_023, Cliente_015, Client...",[Computadores],"[Sul, Sudeste, Nordeste, Norte, Centro-Oeste]","[nan, 9.0, 4.0, 2.0, 7.0, 1.0, 8.0, 6.0, 10.0,...",[3500.0]
Smartphone,"[2024-06-30 00:00:00, 2024-07-21 00:00:00, NaT...","[Cliente_020, Cliente_024, Cliente_011, Client...",[Celulares],"[Sul, Norte, Centro-Oeste, Sudeste, Nordeste]","[6.0, 8.0, nan, 2.0, 10.0, 1.0, 5.0, 9.0, 4.0,...",[2200.0]
Tablet,"[2024-11-05 00:00:00, 2024-07-29 00:00:00, 202...","[Cliente_030, Cliente_004, Cliente_020, Client...",[Celulares],"[Centro-Oeste, Sudeste, Norte, Sul, Nordeste]","[6.0, 7.0, 2.0, 4.0, 5.0, 8.0, 3.0, 10.0, nan,...","[1800.0, nan]"
Teclado,"[2024-03-24 00:00:00, 2024-10-26 00:00:00, 202...","[Cliente_008, Cliente_005, Cliente_020, Client...",[Periféricos],"[Nordeste, Norte, Sul, Sudeste, Centro-Oeste]","[4.0, 5.0, 3.0, 10.0, 8.0, 2.0, 9.0, nan, 1.0,...","[250.0, nan]"

In [ ]:
# Valores não presentes na variavel
df_faltantes = pd.DataFrame(index=df_agrupado.index)
for coluna in df_agrupado.columns:
    universo_global = set(df_limpo[coluna].unique())
    df_faltantes[coluna] = df_agrupado[coluna].apply(
        lambda valores_do_produto: list(universo_global - set(valores_do_produto)))

display(df_faltantes)

,data_venda,cliente,categoria,regiao,quantidade,preco_unitario
produto,,,,,,
Monitor,"[NaT, 2024-08-20 00:00:00, 2024-08-04 00:00:00...","[Cliente_023, Cliente_011, Cliente_008, Client...","[Periféricos, Celulares]",[],[nan],"[1800.0, 3500.0, nan, 120.0, 250.0, 2200.0]"
Mouse,"[2024-08-20 00:00:00, 2024-08-04 00:00:00, 202...","[Cliente_023, Cliente_012, Cliente_003, Client...","[Computadores, Celulares]",[],"[10.0, nan]","[1800.0, 3500.0, 1200.0, nan, 2200.0, 250.0]"
Notebook,"[2024-08-20 00:00:00, 2024-02-29 00:00:00, 202...","[Cliente_020, Cliente_026, Cliente_005, Client...","[Periféricos, Celulares]",[],[nan],"[1800.0, 1200.0, nan, 120.0, 250.0, 2200.0]"
Smartphone,"[2024-08-04 00:00:00, 2024-09-05 00:00:00, 202...","[Cliente_028, Cliente_005, Cliente_012, Client...","[Periféricos, Computadores]",[],[nan],"[1800.0, 3500.0, 1200.0, nan, 120.0, 250.0]"
Tablet,"[NaT, 2024-08-20 00:00:00, 2024-08-04 00:00:00...","[Cliente_028, Cliente_026, Cliente_012, Client...","[Periféricos, Computadores]",[],[nan],"[3500.0, 1200.0, nan, 120.0, 250.0, 2200.0]"
Teclado,"[NaT, 2024-08-20 00:00:00, 2024-08-04 00:00:00...","[Cliente_023, Cliente_011, Cliente_001, Client...","[Computadores, Celulares]",[],[nan],"[1800.0, 3500.0, 1200.0, nan, 120.0, 2200.0]"

In [62]:
# Valores presentes naquele elemento
df_clientes = df_limpo.groupby('cliente').agg(lambda x: list(x.unique()))
#df_datas = df_limpo.groupby('data_venda').agg(lambda x: list(x.unique()))

display(df_clientes)
#display(df_datas)

,data_venda,produto,categoria,regiao,quantidade,preco_unitario
cliente,,,,,,
Cliente_001,"[2024-11-01 00:00:00, 2024-05-16 00:00:00, 202...","[Monitor, Mouse, Smartphone]","[Computadores, Periféricos, Celulares]","[Sudeste, Nordeste, Sul, Centro-Oeste, Norte]","[7.0, 9.0, 3.0, 4.0, 5.0, 2.0]","[1200.0, 120.0, 2200.0]"
Cliente_002,"[2024-03-20 00:00:00, 2024-12-27 00:00:00, 202...","[Mouse, Tablet]","[Periféricos, Celulares]","[Nordeste, Sul, Norte]","[8.0, 3.0, 4.0]","[120.0, nan]"
Cliente_003,"[2024-03-27 00:00:00, 2024-01-10 00:00:00, 202...","[Teclado, Notebook, Monitor, Tablet]","[Periféricos, Computadores, Celulares]","[Sul, Sudeste, Centro-Oeste, Nordeste]","[8.0, 6.0, 7.0]","[250.0, 3500.0, 1200.0, 1800.0]"
Cliente_004,"[2024-07-23 00:00:00, 2024-10-22 00:00:00, 202...","[Mouse, Smartphone, Tablet, Notebook]","[Periféricos, Celulares, Computadores]","[Sul, Centro-Oeste, Sudeste, Norte]","[5.0, 10.0, 7.0, 4.0]","[120.0, 2200.0, 1800.0, 3500.0]"
Cliente_005,"[2024-10-26 00:00:00, 2024-09-16 00:00:00, 202...","[Teclado, Mouse, Monitor, Tablet]","[Periféricos, Computadores, Celulares]","[Norte, Sul, Sudeste, Centro-Oeste]","[5.0, 7.0, 8.0, 3.0, 2.0]","[250.0, 120.0, 1200.0, 1800.0]"
Cliente_006,"[2024-03-26 00:00:00, 2024-02-16 00:00:00]","[Notebook, Mouse]","[Computadores, Periféricos]","[Centro-Oeste, Nordeste]","[4.0, 8.0]","[3500.0, 120.0]"
Cliente_007,"[2024-01-17 00:00:00, 2024-09-07 00:00:00, 202...","[Smartphone, Monitor]","[Celulares, Computadores]","[Norte, Centro-Oeste]","[2.0, 5.0]","[2200.0, 1200.0]"
Cliente_008,"[2024-03-24 00:00:00, 2024-04-22 00:00:00, 202...","[Teclado, Notebook, Mouse, Tablet]","[Periféricos, Computadores, Celulares]","[Nordeste, Sudeste, Centro-Oeste, Norte]","[4.0, 7.0, 5.0, nan, 2.0, 10.0]","[250.0, 3500.0, 120.0, 1800.0]"
Cliente_009,"[2024-02-25 00:00:00, 2024-11-14 00:00:00, 202...","[Monitor, Notebook, Teclado, Smartphone]","[Computadores, Periféricos, Celulares]","[Centro-Oeste, Sul, Sudeste, Nordeste, Norte]","[6.0, 8.0, 1.0, 10.0, 2.0, 9.0]","[1200.0, 3500.0, 250.0, 2200.0, nan]"
Cliente_010,"[2024-02-08 00:00:00, 2024-10-22 00:00:00]","[Mouse, Monitor]","[Periféricos, Computadores]","[Norte, Sudeste]","[4.0, 2.0]","[120.0, 1200.0]"
Cliente_011,"[NaT, 2024-01-22 00:00:00]","[Smartphone, Notebook]","[Celulares, Computadores]","[Centro-Oeste, Sudeste]","[6.0, 10.0]","[2200.0, 3500.0]"
Cliente_012,"[2024-02-08 00:00:00, 2024-06-16 00:00:00, 202...","[Notebook, Monitor]",[Computadores],"[Norte, Sudeste]","[2.0, 5.0, 4.0]","[3500.0, 1200.0]"
Cliente_013,"[2024-06-23 00:00:00, 2024-02-12 00:00:00, 202...","[Mouse, Smartphone, Teclado, Notebook]","[Periféricos, Celulares, Computadores]","[Sudeste, Nordeste, Centro-Oeste, Norte]","[7.0, 1.0, 5.0, 8.0, 9.0]","[120.0, 2200.0, 250.0, 3500.0]"
Cliente_014,"[2024-03-07 00:00:00, 2024-12-15 00:00:00, 202...","[Notebook, Tablet, Smartphone, Mouse]","[Computadores, Celulares, Periféricos]","[Norte, Nordeste, Sudeste]","[6.0, 4.0, nan, 8.0, 9.0]","[3500.0, 1800.0, 2200.0, 120.0]"
Cliente_015,"[2024-05-28 00:00:00, 2024-04-17 00:00:00, 202...","[Notebook, Tablet, Monitor, Smartphone]","[Computadores, Celulares]","[Nordeste, Sul, Sudeste, Norte]","[4.0, 5.0, 6.0, 10.0, 1.0, 8.0]","[3500.0, 1800.0, 1200.0, 2200.0]"
Cliente_016,"[2024-08-06 00:00:00, 2024-10-26 00:00:00, 202...","[Teclado, Monitor, Tablet]","[Periféricos, Computadores, Celulares]","[Centro-Oeste, Sudeste, Norte, Nordeste]","[9.0, 7.0, 5.0, 3.0, 8.0]","[250.0, nan, 1800.0]"
Cliente_017,"[2024-10-26 00:00:00, 2024-07-16 00:00:00, 202...","[Notebook, Teclado, Smartphone, Tablet]","[Computadores, Periféricos, Celulares]","[Sudeste, Norte, Centro-Oeste, Nordeste]","[1.0, 2.0, 4.0, 5.0]","[3500.0, 250.0, 2200.0, 1800.0]"
Cliente_018,"[2024-08-04 00:00:00, 2024-08-14 00:00:00, 202...","[Notebook, Smartphone, Tablet, Teclado]","[Computadores, Celulares, Periféricos]","[Sul, Sudeste, Norte, Centro-Oeste]","[nan, 2.0, 5.0, 10.0, 9.0]","[3500.0, 2200.0, 1800.0, 250.0]"
Cliente_019,"[2024-01-17 00:00:00, 2024-10-31 00:00:00, 202...","[Notebook, Smartphone, Mouse, Teclado]","[Computadores, Celulares, Periféricos]","[Nordeste, Sul, Norte, Centro-Oeste]","[4.0, 2.0, 3.0, 1.0, 7.0]","[3500.0, 2200.0, 120.0, 250.0]"
Cliente_020,"[2024-06-30 00:00:00, 2024-01-25 00:00:00, 202...","[Smartphone, Monitor, Teclado, Tablet, Mouse]","[Celulares, Computadores, Periféricos]","[Sul, Sudeste, Norte]","[6.0, 2.0, 3.0, 5.0, 8.0, 10.0]","[2200.0, 1200.0, 250.0, 1800.0, 120.0]"
Cliente_021,"[2024-03-20 00:00:00, 2024-04-23 00:00:00]","[Mouse, Tablet]","[Periféricos, Celulares]","[Nordeste, Centro-Oeste]","[9.0, 10.0]","[120.0, 1800.0]"
Cliente_022,"[2024-09-05 00:00:00, 2024-07-05 00:00:00, 202...","[Notebook, Mouse, Smartphone, Tablet]","[Computadores, Periféricos, Celulares]","[Centro-Oeste, Sudeste, Norte, Nordeste, Sul]","[2.0, 4.0, 8.0, 6.0, 1.0, nan]","[3500.0, 120.0, 2200.0, 1800.0]"
Cliente_023,"[2024-05-30 00:00:00, NaT, 2024-12-24 00:00:00...","[Notebook, Smartphone, Tablet]","[Computadores, Celulares]","[Sudeste, Centro-Oeste]","[9.0, nan, 8.0]","[3500.0, 2200.0, 1800.0]"
Cliente_024,"[2024-01-13 00:00:00, 2024-07-21 00:00:00, 202...","[Mouse, Smartphone, Notebook, Monitor, Tablet,...","[Periféricos, Celulares, Computadores]","[Norte, Sul, Nordeste, Centro-Oeste]","[2.0, 8.0, 7.0, 5.0, 1.0]","[120.0, 2200.0, 3500.0, 1200.0, 1800.0, 250.0]"
Cliente_025,"[2024-05-15 00:00:00, 2024-05-08 00:00:00, 202...","[Teclado, Tablet, Monitor, Notebook]","[Periféricos, Celulares, Computadores]","[Sul, Sudeste, Norte]","[3.0, 5.0, 7.0, 4.0, 1.0]","[250.0, 1800.0, 1200.0, 3500.0]"
Cliente_026,"[NaT, 2024-07-29 00:00:00, 2024-08-28 00:00:00...","[Mouse, Monitor, Smartphone, Teclado]","[Periféricos, Computadores, Celulares]","[Sul, Sudeste, Centro-Oeste, Nordeste]","[9.0, 6.0, 1.0, 8.0, nan, 4.0]","[120.0, 1200.0, 2200.0, 250.0]"
Cliente_027,"[2024-12-12 00:00:00, 2024-08-30 00:00:00, 202...","[Monitor, Notebook]",[Computadores],"[Sudeste, Sul, Centro-Oeste]","[7.0, 6.0, 4.0]","[1200.0, 3500.0]"
Cliente_028,"[2024-08-08 00:00:00, 2024-06-13 00:00:00, 202...","[Teclado, Monitor]","[Periféricos, Computadores]","[Sudeste, Centro-Oeste]","[3.0, 8.0, 6.0]","[250.0, 1200.0]"
Cliente_029,"[2024-07-04 00:00:00, 2024-06-02 00:00:00, 202...","[Notebook, Mouse, Monitor, Teclado]","[Computadores, Periféricos]","[Norte, Sudeste, Nordeste, Centro-Oeste]","[2.0, 9.0, 3.0, 7.0]","[3500.0, 120.0, 1200.0, 250.0]"
Cliente_030,"[2024-11-05 00:00:00, 2024-01-21 00:00:00, 202...","[Tablet, Teclado, Smartphone]","[Celulares, Periféricos]","[Centro-Oeste, Nordeste, Sudeste]","[6.0, 10.0, 3.0]","[1800.0, 250.0, 2200.0]"

Para ficar fácil de interpretar, nós dividimos esses indicadores em três grupos: os de Texto, os de Média/Dispersão, e os de Posição (Quartis).
1) O Grupo dos Textos (Variáveis Categóricas): unique (qauntos valores unicos), top (moda) e freq (nºx moda aparece)
2) O Grupo de Posição (Os Quartis) e o 50% (Mediana)
--> Sempre confie mais na Mediana (50%) para entender o comportamento do seu "cliente padrão".
--> O método estatístico mais famoso do mundo para detectar outliers usa exatamente eles. Chama-se Método IQR (Intervalo Interquartil).

In [ ]:
# Decisões: Classificação de cliente(quantidade x preco_unitario), Bronze até 9000, Prata até 17600, < Ouro
funcoes.resumo_estatistico(df_original)

,id_venda,data_venda,cliente,produto,categoria,regiao,quantidade,preco_unitario
count,150.0,150,150,150,150,150,144.0,147.0
unique,-,113,30,9,3,5,-,-
top,-,2024-05-15,Cliente_024,Notebook,Celulares,Sudeste,-,-
freq,-,5,8,27,53,42,-,-
mean,75.5,-,-,-,-,-,5.42,1596.12
std,43.45,-,-,-,-,-,2.71,1178.31
min,1.0,-,-,-,-,-,1.0,120.0
25%,38.25,-,-,-,-,-,3.0,250.0
50%,75.5,-,-,-,-,-,5.0,1800.0
75%,112.75,-,-,-,-,-,8.0,2200.0
max,150.0,-,-,-,-,-,10.0,3500.0